name: Release Weekly Docker
on:
  workflow_dispatch:
  repository_dispatch:
    types: 'release-weekly-docker'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zapbot
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: docker/Dockerfile-weekly
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            owasp/zap2docker-weekly:w${{ env.REL_DATE }}
            owasp/zap2docker-weekly:latest
          build-args: |
            WEBSWING_URL=${{ secrets.WEBSWING_URL }}
